### ISSUE TITLE
Graphic Card Optimization may make WPF application render error

### ISSUE THREAD

**Issue by gunslinger23** [semazurek/ET-All-in-One-Optimizer#6]
Some register settings in "Graphic Card Optimization" may break the WPF application render, and will cause render problem. It need to find out and remove 😢

**Comment by semazurek** [comment]
All right I found a way to fix the above errors because I noticed them myself in vegas 19.0. We simply enter the .txt file that I attached earlier and delete all the values ​​​​/keys that are listed there. (Reg-GPU.txt). I'm not closing the thread for now.
