### ISSUE TITLE
Some applications show a white screen

### ISSUE THREAD

**Issue by DJSAKUGA** [semazurek/ET-All-in-One-Optimizer#7]
Hi! I'm using your script with many computers and I like it so much, I'm an IT guy too.
In the last version I've tried all the options in different PCs, but in some applications like DDU or DS4Windows (as example) there's this problem. I'm gonna try all different options and update this! Thanks
![DDU](https://user-images.githubusercontent.com/63500182/207718528-7d04b902-6e3e-4fe7-8518-3170dd20056c.jpg)

**Comment by semazurek** [comment]
Did you use Graphical RAegistry Tweak Option ? In last issue I was able to find out that this could occur by this... To fix that go to regedit -> And remove all dwords that Reg.GPU.reg added. 
Let me know if this is it and may be reinstall graphic driver ok ?

Windows Registry Editor Version 5.00
[HKEY_CURRENT_USER\Software\Microsoft\Avalon.Graphics]
"MaxMultisampleType"=dword:00000004
"DisableHWAcceleration"=dword:00000000
"EnableDebugControl"=dword:00000001
"UseDX9LText"=dword:00000001
"BreakOnUnexpectedErrors"=dword:00000001
"RPCAvalon"=dword:00000001
"RecordAvalonFile"=dword:00000000
"UseReferenceRasterizer"=dword:00000001
"SkipDriverDateCheck"=dword:00000000
"SkipDriverCheck"=dword:00000000
[HKEY_CURRENT_USER\Software\Microsoft\Avalon.Graphics\DISPLAY1]
"PixelStructure"=dword:00000001
"GammaLevel"=dword:00000898
"ClearTypeLevel"=dword:00000064
"EnhancedContrastLevel"=dword:00000190
"GrayscaleEnhancedContrastLevel"=dword:00000190
"TextContrastLevel"=dword:00000002
[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\GraphicsDrivers\Scheduler]
"EnablePreemption"=dword:00000001
[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Watchdog\Logging]
"BreakOnError"=dword:00000001
"BreakOnAssertion "=dword:00000001
[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\GraphicsDrivers]
"TdrLevel"=dword:00000003
"TdrDelay"=dword:00000078
"TdrDdiDelay"=dword:0000003c
"TdrTestMode"=dword:00000000
"TdrDebugMode"=dword:00000002
"TdrLimitTime"=dword:00000078
"TdrLimitCount"=dword:00000005
[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\GraphicsDrivers\BasicDisplay]
"BasicDisplayUserNotified"=dword:00000000
[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\GraphicsDrivers\DCI]
"Timeout"=dword:00000078
[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\GraphicsDrivers\TdrWatch]
"TDR_RECOVERY"=dword:00000001

**Comment by DJSAKUGA** [comment]
All is perfect now, you are the man! Many thanks

**Comment by semazurek** [comment]
No problem 😊👍 I am here to help You.
